[tool.poetry]
name = "service"
version = "0.1.0"
description = "Rota generator"
authors = ["Ben Roberts <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.7"
XlsxWriter = "^1.1"

[tool.poetry.dev-dependencies]
pytest = "^4.4"
pytest-clarity = {version = "^0.1.0-alpha.1",allows-prereleases = true}

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
